### PR TITLE
Added -it switch to Docker examples to get into the command line

### PR DESCRIPTION
**Pull request by yooakim**
As the purpose of the CLI is to use the command line I've added the `-it` parameter to the Docker example command lines.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/install-azure-cli.md** | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/install_azure_cli_md_GitHub_49c1a1562f893cf6_28052_report.xml?apikey=g9b4j3M92NgWArBSJLi7-6OmgcjpuOe26bH3ODesxnTfAjZ-uWdkfq6FZHSf83oviDam1dwD3FrblpHDG0e4acyjJ8ifikbqCpzkMI3t2Lk%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileLoadException: Could not load file or assembly &#39;System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: &#39;System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; ---&gt; System.IO.FileLoadException: Could not load file or assembly &#39;System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: &#39;System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39;

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C17%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704170638349709-312%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/Azure/azure-docs-cli-python, working directory: W:\3out-s, target branch: master, target branch commit: 7dda37ec30654d373ffd91f74b4e505c12ff49ec, source branch: 54cfd2116c9c4215575c674bc6df79a3/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C28%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706282148303387-312%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
@rloutlaw - Seems like `-it` changes this from being "install instructions" to "execution instructions". Deferring to your judgement on this merge but it looks like `-it` was removed in a previous commit.

**Comment by sptramer** [comment]
@yooakim Please rebase the current `master` into your branch to resolve conflicts if you are interested in still having this PR evaluated and merged.

**Comment by sptramer** [comment]
This PR has not been updated with a rebase and will be closed in favor of #524 being merged.

**Pull request closed without merging**
