### PR TITLE
updating TOC and index files

### PR DESCRIPTION
**Pull request by barlanmsft**
- fixed word wrap 
- changed title in index

### CODE REVIEW

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/barlanmsft/azure-docs-cli-python/blob/master/docs-ref-conceptual/TOC.yml) | :x:Error | | [Details](#user-content-docs-ref-conceptual%2FTOC.yml)
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs-ref-conceptual%2FTOC.yml"></a>
### [docs-ref-conceptual/TOC.yml](https://github.com/barlanmsft/azure-docs-cli-python/blob/master/docs-ref-conceptual/TOC.yml)
 - **[Error]** W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..
 - **[Error]** Unable to load file: docs-ref-conceptual/TOC.yml via processor: ExperimentalTocDocumentProcessor: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..
 - **[Error]** W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..
 - **[Error]** Unable to load file: docs-ref-conceptual/TOC.yml via processor: TocDocumentProcessor: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.Common.TocItemViewModel, Microsoft.DocAsCode.DataContracts.Common, Version=2.22.1.0, Culture=neutral, PublicKeyToken=null
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(IParser reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(IParser parser, Type type, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](TextReader reader)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   at Microsoft.OpenPublishing.PluginHelper.TocHelper.InjectTocMetadata(String tocPath, String metaName, String metaValue)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **[Error]** W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..
 - **Line 81**: **[Error]** W:\xzl4-s\.optemp\packages\opbuild.scripts.1.49.3\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset azure-cli-docs
 - **Line 80**: **[Warning]** Failed to run script W:\xzl4-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.Common.TocItemViewModel, Microsoft.DocAsCode.DataContracts.Common, Version=2.22.1.0, Culture=neutral, PublicKeyToken=null
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(IParser reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(IParser parser, Type type, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](TextReader reader)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   at Microsoft.OpenPublishing.PluginHelper.TocHelper.InjectTocMetadata(String tocPath, String metaName, String metaValue)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
 - **[Error]** W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC File: W:\xzl4-s\docs-ref-conceptual\TOC.yml is not a valid TOC file, detail: (Line: 69, Col: 22, Idx: 2867) - (Line: 69, Col: 22, Idx: 2867): Mapping values are not allowed in this context..
 - **Line 81**: **[Error]** W:\xzl4-s\.optemp\packages\opbuild.scripts.1.49.3\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset azure-cli-docs
 - **Line 80**: **[Warning]** Failed to run script W:\xzl4-s\_dependentPackages\CommonPlugins\tools\JoinTOC.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201805022223362398-782%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fLyXm4THGAUrcb8mH%2BSmt5wirUe712mSnOHjZ9LL6Ks%3D&st=2018-05-02T22%3A19%3A55Z&se=2018-06-02T22%3A24%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/barlanmsft/azure-docs-cli-python/blob/master/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-782) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-latest&branch=pr-en-us-782) (azure-cli-latest) |
[docs-ref-conceptual/index.md](https://github.com/barlanmsft/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-latest&branch=pr-en-us-782) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-782) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201805022225516477-782%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5qtUolSByOXl9zoheAPh7ze3%2BHeow7mGpUwttrK%2BssU%3D&st=2018-05-02T22%3A24%3A35Z&se=2018-06-02T22%3A29%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
I think this naming works a lot better. Is this to be merged Monday AM? It will go live with the 3PM publish.

Thanks for making a single PR as well.

**Comment by arob98** [comment]
given comments from @sptramer , i approve

**Comment by sptramer** [comment]
Site seems to be live, merging for 3PM publish.

**Pull request merged**
