### PR TITLE
[US-1020102] Install instruction changes

### PR DESCRIPTION
**Pull request by sptramer**
- Reordered install instructions
- Clarified language usage (Azure CLI vs. the CLI)
- Consistency of instructions to use 'az'

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1020102/install-instruction-reorder/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706212058233586-402%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1020102/install-instruction-reorder/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706212102308880-402%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1020102/install-instruction-reorder/docs-ref-conceptual/install-azure-cli.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-402) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli.md)

<a name="docs-ref-conceptual%2Finstall-azure-cli.md"></a>
### [docs-ref-conceptual/install-azure-cli.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1020102/install-instruction-reorder/docs-ref-conceptual/install-azure-cli.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/cli/azure/component#update).
 - **Line 61**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/cli/azure/component).
 - **Line 90**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/cli/azure/component).
 - **Line 126**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/cli/azure/component).
 - **Line 190**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/cli/azure/component#update).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706212126395846-402%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1020102/install-instruction-reorder/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-402) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706212141141615-402%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
#sign-off

**Pull request merged**
