### PR TITLE
Azure CLI 2.0.34 Release Notes

### PR DESCRIPTION
**Pull request by troydai**
@sptramer @twitchax

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-3/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-858) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-858) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C1%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806011827513876-858%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=J0Y1t2VW7hL2QVCxBij2bxMjgnIEa04L727lSaB03NI%3D&st=2018-06-01T18%3A26%3A04Z&se=2018-07-02T18%3A31%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-3/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-858) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-858) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C1%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806011958476774-858%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AyhD9VRqQXGBRHuexjLJGlbRTRYLulY2KzaSgw1M0LQ%3D&st=2018-06-01T19%3A56%3A45Z&se=2018-07-02T20%3A01%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
__MERGE DATE:__ 6/5

**Comment by troydai** [comment]
Thank you.

**Pull request merged**
