### PR TITLE
Update TOC.md

### PR DESCRIPTION
**Pull request by czeumault**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/TOC.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/TOC_md_GitHub_43b6dedc5117b544_29857_report.xml?apikey=MSEjU2yllOnAPZWtZlvJ8J24loM3TGV1v0R9R-xMxecwsYeSggKweDWDCvkGglUzjX3iL9XKoKGxxip13rlsMfWKmUrQTFJfbwXW--t0D6E%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-2/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705221539481564-368%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/TOC.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/TOC_md_GitHub_43b6dedc5117b544_30004_report.xml?apikey=SGSQ447WUwJF7GZb80Tj4k1ZcohPHrKR6wW2XK5-_jPZ2i_AacTjFNTgcRduXy9z9xonL528Bgxrd-sBRqoZ3s1iYtHbdOachxjYBDfj9y0%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/TOC.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/TOC_md_GitHub_43b6dedc5117b544_30011_report.xml?apikey=OgTC8vZdrPcnKiuv38T7imsbF21KXOHwZfvBjLMax8iafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KT-uEOEhslVoeShKNYw8sFGc%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-2/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705221547310053-368%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-2/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705221547550111-368%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/TOC.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/TOC_md_GitHub_43b6dedc5117b544_30078_report.xml?apikey=QF9DD00mSIGm0_n07kbO89gNFwsamoTgXTggQpDAWiCs0TJw6VhGSu8cGxS2uCt_j814fGJHmNxjX2_dICm7EntlMWIBX65FvJde1cW0oX8%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-2/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705221551314766-368%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/TOC.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/TOC_md_GitHub_43b6dedc5117b544_34849_report.xml?apikey=R-4uEM3YWm_sJ9d0y6lVU4WZY8Pl23Bfvtf_YpGjS7ys0TJw6VhGSu8cGxS2uCt_Bg8lsh9anMEhVgB1pEvDPJphUBObArvhugAt-ZngcuM%3D) |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$

- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-2/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705222010058299-368%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
@rloutlaw - Some of the wording of the ToC seems to have been improved, some changes may not be necessary. Will let you have final say.

**Comment by sptramer** [comment]
ToC has been independently updated to include many of these changes. If further changes are required then a new PR or VSTS ticket can be created. Closing.

**Pull request closed without merging**
