### PR TITLE
M5157: Incomplete sentence: "missed help for access show. adding it."

### PR DESCRIPTION
**Pull request by carolinacmoravia**
@routlaw, 
Could you review this and reply, please? Many thanks in advance.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/release-notes-azure-cli.md** | 72 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/release_notes_azure_cli_md_GitHub_43b6dedc5117b544_58085_report.xml?apikey=8xMktCLOlq2TilJZF5A6LmfvJ5XpfK4LXTTGP29kaz4_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQD28TmdFlW4w6H6nZVE5dCbs%3D) |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$

- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/carolinacmoravia/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?branch=pr-en-us-375) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C29%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705291848101848-375%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
@routlaw,
Could you review this and reply, please? Many thanks in advance.

**Comment by sptramer** [comment]
@rloutlaw - Required localization fix. Should create a VSTS bug for it to track if necessary.

**Comment by v-jotel** [comment]
@routlaw,
Would you kindly help to review this, please?
Many thanks in advance.

**Comment by carolinacmoravia** [comment]
@routlaw,
Would you kindly help to review this, please?
Many thanks in advance.

**Comment by carolinacmoravia** [comment]
@routlaw,
Verified that reported issues still reproduces on current version of this file. Would you kindly help to review this, please? 
Thank you.

Cc: @SunnyDeng

**Comment by sptramer** [comment]
@carolinacmoravia - Please file a VSTS issue internally to resolve this. Release notes for previous versions are normally not updated. Closing this PR as it is a bug report.

**Pull request closed without merging**
