### PR TITLE
Update install-azure-cli.md.

### PR DESCRIPTION
**Pull request by twitchax**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Error when get composition container: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information., loader exceptions: Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;., Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;., Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;., Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;., Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;., Could not load type &#39;Microsoft.DocAsCode.Plugins.ICanTraceContextInfoBuildStep&#39; from assembly &#39;Microsoft.DocAsCode.Plugins, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null&#39;.
 - **[Error]** System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.&lt;WithAssemblies&gt;b__0(Assembly a)
   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__14`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.DocAsCode.Common.CompositionUtility.GetContainer(IEnumerable`1 assemblies)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder..ctor(IEnumerable`1 assemblies, ImmutableArray`1 postProcessorNames, String templateHash, String intermediateFolder, String commitFromSHA, String commitToSHA)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C27%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703272311165268-260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by allclark** [comment]
Closing to rerun build

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/twitchax/azure-docs-cli-python/blob/twitchax-patch/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-260) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C28%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703281711421947-260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by twitchax** [comment]
Thanks, @allclark!

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/Azure/azure-docs-cli-python, working directory: W:\ruj5-s, target branch: live, target branch commit: 2fbfafa970ee8780378303853de50864adf5d4f3, source branch: 746fc093004364d810dc1e0fd79b57d3/twitchax-patch, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C28%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706282048201528-260%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
The install instructions (correctly) no longer reference the `-it` options; this is an install-only. In the future we may want to revisit instructions on using the CLI with Docker.

**Pull request closed without merging**
