### PR TITLE
Available extensions page

### PR DESCRIPTION
**Pull request by derekbekoe**
Please ignore this PR for now.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802262328449130-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DjOKBuHOxq9MG7orJ%2BrEU7ECKUzqDqBbdUv%2Fl0Hjgdw%3D&st=2018-02-26T23%3A26%3A25Z&se=2018-03-29T23%3A31%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802262337066153-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eIex1aau25A7B%2BN9LXKdkmwxuP6zUwCzOFZS4D7uXug%3D&st=2018-02-26T23%3A34%3A44Z&se=2018-03-29T23%3A39%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802262345325863-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w7C8%2FEARduDrsZeMI6HLXT8TaelXRza8DMpyajIhgJY%3D&st=2018-02-26T23%3A43%3A00Z&se=2018-03-29T23%3A48%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802262352313917-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3Bkv5Uz8AAjVriCTyzQA%2BC63Np01%2BQvV8VIrwdacvIA%3D&st=2018-02-26T23%3A50%3A02Z&se=2018-03-29T23%3A55%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C27%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802262359327753-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qkZ9j9i6YJROdPcDiHpvr6qjtznWkPL1d3UxhX7SMpE%3D&st=2018-02-26T23%3A56%3A58Z&se=2018-03-30T00%3A01%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C8%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201803081857186235-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RNTUXPTfkJF2vJhok3sV1mvsH8MCXgAF3J%2Fb7aM50x4%3D&st=2018-03-08T18%3A54%3A52Z&se=2018-04-08T18%3A59%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C8%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201803081905049571-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Az0N%2FogSqOWdKjdjLRqlqbk4wJIOIUsvy1tGGAqX6zI%3D&st=2018-03-08T19%3A02%3A45Z&se=2018-04-08T19%3A07%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C8%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201803081920373731-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PFAdNS0RNQIOQJgLmIsWzkb3snpT8xcvDDhCGXGvMpI%3D&st=2018-03-08T19%3A18%3A08Z&se=2018-04-08T19%3A23%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C15%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201803151753153355-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=z4%2BCclzrntTUm1RSQpLxI2XVghY3ARNUicelfftx5cE%3D&st=2018-03-15T17%3A51%3A37Z&se=2018-04-15T17%3A56%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest) |
[docs-ref-conceptual/azure-cli-available-extensions.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/extensions-available/docs-ref-conceptual/azure-cli-available-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-latest&branch=pr-en-us-658) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-available-extensions?view=azure-cli-2017-03-09-profile&branch=pr-en-us-658) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C15%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201803151755484623-658%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5RKWQ01vrvH%2FESKE3hfTVxYggaySt6%2FHD%2FZYJ0krLWw%3D&st=2018-03-15T17%3A54%3A30Z&se=2018-04-15T17%3A59%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
Closing in favor of #692

**Pull request closed without merging**
