### PR TITLE
Update get-started-with-azure-cli.md

### PR DESCRIPTION
**Pull request by czeumault**
Added az login after install sentence

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/czeumault-patch-3/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?branch=pr-en-us-397) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C17%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706171830099044-397%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
@rloutlaw - Seems like an important contribution but is missing additional information + links to login. Leaving to you to review and arbitrate.

**Comment by sptramer** [comment]
@czeumault - Please rebase `master` onto your branch if you are still interested in having this PR evaluated and merged.

**Comment by sptramer** [comment]
Closing in favor of #489.

**Pull request closed without merging**
