### PR TITLE
[US-1013585] Add samples to TOC

### PR DESCRIPTION
**Pull request by sptramer**
Exactly what it says it does on the cover.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1013585/toc-update/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C23%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706232257216175-408%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/TOC.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1013585/toc-update/docs-ref-autogen/TOC.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/cosmosdb/database?branch=pr-en-us-408) |
[docs-ref-conceptual/TOC.md](https://github.com/sptramer/azure-docs-cli-python/blob/US-1013585/toc-update/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C23%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706232314295698-408%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
#sign-off

**Comment by rloutlaw** [comment]
Reviewed and links are in good order, merging.

**Pull request merged**
