### PR TITLE
correcting the installation instructions. --user for pip is wrong

### PR DESCRIPTION
**Pull request by chkuhtz**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/chkuhtz/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-242) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C19%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703190102250647-242%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by allclark** [comment]
omitting --user has it's own downside. I think that the changes we made recently to the PATH note have helped with the problems users were having. @twitchax what's your guidance on this?

**Comment by twitchax** [comment]
@derekbekoe might be able to provide better context, but I am certain we want to keep `--user` for Windows, at a minimum.

**Comment by derekbekoe** [comment]
Yes I would vote to keep `--user`.
Omitting it has it's own issues with user permissions, requiring admin prompt, etc.

**Comment by allclark** [comment]
OK. We've made some other changes that should help with the problems that users are facing.

**Comment by chkuhtz** [comment]
The real issue here for --user is that a semantic is implied: only install for me, rather than system wide.  This is a pip semantic and should be made clear in the context of the doc: you're installing this just for yourself with --user, this is the path for it, bla bla bla.  if you want to install this system wide, do xyz and add path bla.  We can't just gloss over this and make an assumption on behalf of the user that they only meant to install this for themselves.  We're exposing semantic of pip here which has nothing to do with the cli itself and must explain it.

**Comment by twitchax** [comment]
@chkuhtz, that makes sense.

@derekbekoe, how would you feel about adding some language around each of the options.  I am tempted to leave it as `pip install --user azure-cli`; then, we can add a note that `--user` is the recommended install path, but it is not required.  Then, maybe link to https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-user.

**Comment by derekbekoe** [comment]
Adding a note that `--user` is optional makes sense.

**Pull request closed without merging**
