### PR TITLE
MS Learn cross-promo links

### PR DESCRIPTION
**Pull request by mtillman**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-cli-2017-03-09-profile/TOC.json](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/azure-cli-2017-03-09-profile/TOC.json) | :warning:Warning | | [Details](#user-content-azure-cli-2017-03-09-profile%2FTOC.json)
[docs-ref-conceptual/index.md](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-latest&branch=pr-en-us-1041) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1041) (azure-cli-2017-03-09-profile) |

<a name="azure-cli-2017-03-09-profile%2FTOC.json"></a>
### [azure-cli-2017-03-09-profile/TOC.json](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/azure-cli-2017-03-09-profile/TOC.json)
 - **[Warning]** Error happen when converting azure-cli-2017-03-09-profile/TOC.json to Pdf. Details: The process cannot access the file &#39;W:\l0pp-o-unknown\azure-cli-docs_en-us_TOC.pdf&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201809221704388795-1041%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FZ%2BNyUhfvdXL0fwKO6mn0W4t%2FDVhBaHXUrw%2BW2lkvl0%3D&st=2018-09-22T17%3A04%3A11Z&se=2018-10-23T17%3A09%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azure-cli-2017-03-09-profile/TOC.json](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/azure-cli-2017-03-09-profile/TOC.json) | :warning:Warning | | [Details](#user-content-azure-cli-2017-03-09-profile%2FTOC.json)
[docs-ref-conceptual/index.md](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-latest&branch=pr-en-us-1041) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1041) (azure-cli-2017-03-09-profile) |

<a name="azure-cli-2017-03-09-profile%2FTOC.json"></a>
### [azure-cli-2017-03-09-profile/TOC.json](https://github.com/mtillman/azure-docs-cli-python/blob/patch-1/azure-cli-2017-03-09-profile/TOC.json)
 - **[Warning]** Error happen when converting azure-cli-2017-03-09-profile/TOC.json to Pdf. Details: The process cannot access the file &#39;W:\l3ow-o-b2dc0068\azure-cli-docs_en-us_TOC.pdf&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C22%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201809221713181689-1041%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IrmlsfYfDlJwKWFklFcErOrS000MSWlL79ZhmapH7%2Bo%3D&st=2018-09-22T17%3A12%3A59Z&se=2018-10-23T17%3A17%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mtillman** [comment]
#sign-off

**Comment by SyntaxC4** [comment]
@arob98 @jenniehubbard can you please sign off on this PR

**Comment by JennieHubbard** [comment]
@mtillman @SyntaxC4 @arob98 

Approved

**Comment by arob98** [comment]
#approve #sign-off

**Comment by mtillman** [comment]
@SyntaxC4 Can you merge this one?

**Pull request merged**
