### PR TITLE
fix grammatical issues and single installer

### PR DESCRIPTION
**Pull request by cicorias**
Not sure what "either" applies to as only Homebrew is now listed.

Advise if the script on demand is no longer supported . ie.
```
curl -L https://aka.ms/InstallAzureCli | bash
```

While that script does work, it's no longer clearly visible on the macOS install guide. So, is Homebrew the only way supported in the future? Please say "NO" - many of us are not full Brew fans.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/cicorias/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/install-azure-cli-macos.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest&branch=pr-en-us-630) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-2017-03-09-profile&branch=pr-en-us-630) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C12%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802121449435720-630%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fLXJ%2BKZFD4DNXZ4YBrxnFmTXeWTuI%2B9Fr65egPcVHUc%3D&st=2018-02-12T14%3A47%3A34Z&se=2018-03-15T14%3A52%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
macOS is a version of UNIX supported by the installation script, so you can still follow the [Linux manual instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest).

**Comment by cicorias** [comment]
I get that, but current Doc doesn’t say that. Should it be added back in? What’s the path forward?

**Comment by sptramer** [comment]
The official recommendation is that if a package manager is available, it should be used instead of any manual installation.

**Pull request merged**
