### PR TITLE
devlang and service metadata

### PR DESCRIPTION
**Pull request by allclark**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/format-output-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/format-output-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/overview.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/overview?branch=pr-en-us-263) |
[docs-ref-conceptual/query-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?branch=pr-en-us-263) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C28%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703281644208109-263%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/format-output-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/format-output-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/overview.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/overview?branch=pr-en-us-263) |
[docs-ref-conceptual/query-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-263) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/allclark/azure-docs-cli-python/blob/master/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?branch=pr-en-us-263) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C28%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703281644579772-263%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/authenticate-azure-cli.md** | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/authenticate_azure_cli_md_GitHub_cd8553286ce8ff28_2976_report.xml?apikey=hcI-SiZI9CN09yh-IIUgJlyBLBiESViruwqSdM3reHs_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQD7YFWd8fxb2OmfzfLPWa0V4%3D) |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_cd8553286ce8ff28_2977_report.xml?apikey=anhx72-Df6luHR24cVLtpSW1ddZiriS9Eit2wu2znPKtQJECqYluqVMvea_cgvu0Sbw_FAaFvSSyP0cW5HXH3Rz-CG9Rr7wu-okYjCeNjhU%3D) |
| **docs-ref-conceptual/format-output-azure-cli.md** | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/format_output_azure_cli_md_GitHub_cd8553286ce8ff28_2978_report.xml?apikey=CKro6ViTGE4A2JF8FeajWiw-49LE8YGD07mRF8nwon7fAjZ-uWdkfq6FZHSf83ovnwD0F-lDjbTDhzdZJCdt5AZWYBae156TpCJSFyb-U9U%3D) |
| **docs-ref-conceptual/get-started-with-azure-cli.md** | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/get_started_with_azure_cli_md_GitHub_cd8553286ce8ff28_2979_report.xml?apikey=b-vHY-t1HQLCByh278Lc9rtm3O1XR_-4q2Rqdi3qctbfAjZ-uWdkfq6FZHSf83ovvygepKHFaQg3Nmhuj01CQ6a4Is8o9OcVKcMLG-A3wNA%3D) |
| **docs-ref-conceptual/install-azure-cli.md** | 86 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/install_azure_cli_md_GitHub_cd8553286ce8ff28_2980_report.xml?apikey=r2FUOwiV-Qo88gfbNjoFnAErdfRb0NQqSImX6QNfb-L5cy9VjfuwkEaFMTibOX9aktxRENYiAsPdlP60mk374vMvImW2rGyS1sHF748PrrI%3D) |
| **docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md** | 85 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/manage_azure_subscriptions_azure_cli_md_GitHub_cd8553286ce8ff28_2981_report.xml?apikey=RTSxvwEBsYg7g9wfIPkKXE0NC5HEjgQST6YpjHvyYrKM-Uv53cnBClYGYs9UU--RRgQcIX4rAyjbLMez-o15JOYBRBW0LPXRQ-twa0IdW68%3D) |
| **docs-ref-conceptual/overview.md** | 83 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/overview_md_GitHub_cd8553286ce8ff28_2982_report.xml?apikey=WQ4lwBjWKJdXZT9QYYphFvAjBs3CQotvUQKd87O-Aab5cy9VjfuwkEaFMTibOX9aE1NCumW9WRvZFobWzwU--zs7Dl6OPTI3Hzz9JzOJtPs%3D) |
| **docs-ref-conceptual/query-azure-cli.md** | 76 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/query_azure_cli_md_GitHub_cd8553286ce8ff28_2983_report.xml?apikey=A6hQloihcbEIQC8YQay1046sQhPOymPX5-KDKE03aluM-Uv53cnBClYGYs9UU--RRgQcIX4rAyjbLMez-o15JGgZ92lAJAkqjs7cQVvW2cw%3D) |
| **docs-ref-conceptual/release-notes-azure-cli.md** | 83 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/release_notes_azure_cli_md_GitHub_cd8553286ce8ff28_2984_report.xml?apikey=zoR0X8XYZoWbbD7XIEnvo20Vr0Z2btseKRB0YLQ5OnaM-Uv53cnBClYGYs9UU--RRgQcIX4rAyjbLMez-o15JDdt3x48o5aybMhOfyw5ork%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/authenticate-azure-cli.md** | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/authenticate_azure_cli_md_GitHub_cd8553286ce8ff28_2989_report.xml?apikey=u9wEx9BAAZiZlwEQQR5RIRcABmwEzK8vctzgMc6hXdjfAjZ-uWdkfq6FZHSf83ovm4mJhe7TZaweUV5fd_Mhqw5tgqmG4UF4mdtZIBgmjpM%3D) |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_cd8553286ce8ff28_2990_report.xml?apikey=clYpiTwVX3oopLgSQrKLnvCWJzqiyQlJJHtwQeq4_NnfAjZ-uWdkfq6FZHSf83ovHR0_w5KuqU5NSU8mcnuDXXoD3VqGyrP90hqym7XgDAs%3D) |
| **docs-ref-conceptual/format-output-azure-cli.md** | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/format_output_azure_cli_md_GitHub_cd8553286ce8ff28_2991_report.xml?apikey=6x0RMoNRVSK6QEs7OGSHuLwViX54oAMx53Z63hvtk5vfAjZ-uWdkfq6FZHSf83ovcULRPCnuRBYc6A1u4-cY88VvZrHX_8yP-fqDmxxZvJc%3D) |
| **docs-ref-conceptual/get-started-with-azure-cli.md** | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/get_started_with_azure_cli_md_GitHub_cd8553286ce8ff28_2992_report.xml?apikey=2Zata-PEiLv9paTPKLbjnamnZDPve-GRADECu_8r0Eg_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQD4oiXtYcakQSwnM4w8XS7AQ%3D) |
| **docs-ref-conceptual/install-azure-cli.md** | 86 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/install_azure_cli_md_GitHub_cd8553286ce8ff28_2993_report.xml?apikey=gFvArdBtjznR2_1HxZYJoikMKmkcaHFmKDOgk-cLKUKM-Uv53cnBClYGYs9UU--RRgQcIX4rAyjbLMez-o15JKXRUqyhr9p3eYgD4FGI_Ss%3D) |
| **docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md** | 85 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/manage_azure_subscriptions_azure_cli_md_GitHub_cd8553286ce8ff28_2994_report.xml?apikey=bRtWwy1gmjB2vaGKN1OlBpYgkpWLb4Tsvmovq8b9VI75cy9VjfuwkEaFMTibOX9a5bUNcn-ez2MNcGtnj4kttd0Er_i9tTNwYYDQ0qVBNn4%3D) |
| **docs-ref-conceptual/overview.md** | 83 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/overview_md_GitHub_cd8553286ce8ff28_2995_report.xml?apikey=ncu2FdNMxmpMlm4vICgvAz5w3_XF7LkTNL9S0QigKq45qs5LLTU5PfXgmq-zhMv0_LTIk0HvaeSZsG-2WICjWWloMzgVuEqXLk44g9nz0Cg%3D) |
| **docs-ref-conceptual/query-azure-cli.md** | 76 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/query_azure_cli_md_GitHub_cd8553286ce8ff28_2996_report.xml?apikey=QCM_3Pl_dV8G_YLWvVUmtIucGJXZr6Jlee53-gkBz9kwsYeSggKweDWDCvkGglUzjX3iL9XKoKGxxip13rlsMWzmRQ7nEV7tpeg2Mwa02Ng%3D) |
| **docs-ref-conceptual/release-notes-azure-cli.md** | 83 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/release_notes_azure_cli_md_GitHub_cd8553286ce8ff28_2997_report.xml?apikey=JsFT702cK4cs8ugFJFWMjRUh85b6OUH2zAL-OPr8PxzfAjZ-uWdkfq6FZHSf83ovnxT_-iVeYynUCGgSrbtJRT8kIyCRqP9GIDNQTyBrAXM%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Pull request merged**
