### PR TITLE
updates for cloud shell and try it feature

### PR DESCRIPTION
**Pull request by rloutlaw**
Adding in the cloud shell feature and "try it now!" button to most CLI snippets in the conceptual content.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/authenticate-azure-cli.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/authenticate_azure_cli_md_GitHub_43b6dedc5117b544_63822_report.xml?apikey=5zUAU3HbL4R1TQ-L5tWuPMgQ5gVfnfB-5cI44cHH5XMH1XvwdolwVvfaM16gG6WKXWEvV9SnwER8t3bvGu9XE_beFtoCInBoDvU9rb7gZLs%3D) |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_43b6dedc5117b544_63823_report.xml?apikey=VbwQ7apASUmRytfZhrLIfju2gpvt7Wny6IaYcc_sH7etQJECqYluqVMvea_cgvu0hy2V8-dK16p1sDml7e-vpuxSZB3HsabFn-Evbyygc0s%3D) |
| **docs-ref-conceptual/format-output-azure-cli.md** | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/format_output_azure_cli_md_GitHub_43b6dedc5117b544_63824_report.xml?apikey=cFCaNpRSv7RS2MNyNNLCnDFbAN7Kv45JvWg4v3lWP0c_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQD5dl9VIPJXLSe4ON0NayUCA%3D) |
| **docs-ref-conceptual/get-started-with-azure-cli.md** | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/get_started_with_azure_cli_md_GitHub_43b6dedc5117b544_63825_report.xml?apikey=B84lQRbHIZEwb1oRgADkT0STv3wgnhnONdNh7WQAvhO_Lixv3qAuz2dYshS5S0TVHSf9WJilGuqttWV8jGs3bWt9IuFyG6fiH1KadfImHdI%3D) |
| **docs-ref-conceptual/includes/cloud-shell-try-it.md** | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/cloud_shell_try_it_md_GitHub_43b6dedc5117b544_63826_report.xml?apikey=ks3RKpEvk6-N93Vm3B0lWm61gIFafYperGd7EhXSRN_fAjZ-uWdkfq6FZHSf83ov7nf1JQAzy-s0ot97MCPhXJ3YsnslVaNrcW5wW9w7USc%3D) |
| **docs-ref-conceptual/includes/interactive-login.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/interactive_login_md_GitHub_43b6dedc5117b544_63827_report.xml?apikey=oKU1J5P3srpsiZ9n_Vj6B6mLlxa08_B-xh2G6m9j6ebfAjZ-uWdkfq6FZHSf83ovtvu2mMziUMvbQNFRwgzG9gRlcodqhOlMhKr9joZ7ars%3D) |
| **docs-ref-conceptual/install-azure-cli.md** | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/install_azure_cli_md_GitHub_43b6dedc5117b544_63828_report.xml?apikey=3QjDtwAGnftlGaBBjbRDQGTWpkxNYecOVyxEpsfm5QY_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQDwstuzsvb9PeLBQQ9zg-xJA%3D) |
| **docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/manage_azure_subscriptions_azure_cli_md_GitHub_43b6dedc5117b544_63829_report.xml?apikey=0_VfPhUTHxDiFeiMk03lLMZKZwysmlJ9xd6IhGEUW1SafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KT5RZnom7BLc47S7mqjDI4QY%3D) |
| **docs-ref-conceptual/overview.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/overview_md_GitHub_43b6dedc5117b544_63830_report.xml?apikey=dNvu3u-3EW8eTICfFaumX6DK8XX2eeXwltAuwPDctwU_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQDxed_1OfW-YATfjA8LCGB5U%3D) |
| **docs-ref-conceptual/query-azure-cli.md** | 82 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/query_azure_cli_md_GitHub_43b6dedc5117b544_63831_report.xml?apikey=aaPWD6n_l6J7rL3PfAYVZygIimkb1WEec7WlTo1R1SE_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQDwqZtX8AO3V-YVIJ58GoQM0%3D) |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$

- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/format-output-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/format-output-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/includes/cloud-shell-try-it.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/includes/cloud-shell-try-it.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/includes/cloud-shell-try-it?branch=pr-en-us-380) |
[docs-ref-conceptual/includes/interactive-login.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/includes/interactive-login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/includes/interactive-login?branch=pr-en-us-380) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/media/cloud-shell-try-it/cs-button.png](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/media/cloud-shell-try-it/cs-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/overview.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/overview?branch=pr-en-us-380) |
[docs-ref-conceptual/query-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-380) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C2%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706022317021655-380%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/authenticate-azure-cli.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/authenticate_azure_cli_md_GitHub_43b6dedc5117b544_63838_report.xml?apikey=KWv81C83OFE184r2xCJPOts4DICy0v4qsa9VqNqjOwPfAjZ-uWdkfq6FZHSf83ovsIT4Skrn6Zus_16YK0Tcup8hD7HfCsUoo-by9WXO0_o%3D) |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_43b6dedc5117b544_63839_report.xml?apikey=VokvkytYwdxpXGdRXV2MzirhJdAHqTr16o5mVuefrjis0TJw6VhGSu8cGxS2uCt_EdsctqfJnspNjdMNWr2RmVUrRN5T8t6LcNxxiRIDWds%3D) |
| **docs-ref-conceptual/format-output-azure-cli.md** | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/format_output_azure_cli_md_GitHub_43b6dedc5117b544_63840_report.xml?apikey=c9JjPPK1QVwuvDpnh2M_IJG8mf9WmEfTfXozHpmvb1w_sQ6VRqwHG80ru4xSW4M6QCpKZ6hCS3cbFiSWRagQDyn-XROGOygdBRkUUzdAAdk%3D) |
| **docs-ref-conceptual/get-started-with-azure-cli.md** | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/get_started_with_azure_cli_md_GitHub_43b6dedc5117b544_63841_report.xml?apikey=l_k2SLjbn4jFdhp9QGPoZdKwsDj8Q75qB9nZZWZV1zcwsYeSggKweDWDCvkGglUzjX3iL9XKoKGxxip13rlsMUr7rgsl4Ejm-Wlv_l9QI28%3D) |
| **docs-ref-conceptual/includes/cloud-shell-try-it.md** | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/cloud_shell_try_it_md_GitHub_43b6dedc5117b544_63842_report.xml?apikey=rS-0EjtbGncT8SNTqHV7qd--TfRdKzD0nou-NUBVNaytQJECqYluqVMvea_cgvu0S1L2BO8DzPjQ2srlbneCyKLIAQHtzxhzWnoAF8yct5c%3D) |
| **docs-ref-conceptual/includes/interactive-login.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/interactive_login_md_GitHub_43b6dedc5117b544_63843_report.xml?apikey=kYOg71Xwht36LX6hv74qw4BFplvr-fTb4V-bhJMHt-HfAjZ-uWdkfq6FZHSf83ovn7_fW8-W2ahF-u6fPxfvf7ZTqnizjblUeTeRL4jJTUg%3D) |
| **docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/manage_azure_subscriptions_azure_cli_md_GitHub_43b6dedc5117b544_63844_report.xml?apikey=lTTG3kSlfvT1nL_TFfsfHzx56m0b80oJyotUfIQAzLGafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KT1lAMtS5KwCFB9hoFyUYCfE%3D) |
| **docs-ref-conceptual/overview.md** | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/overview_md_GitHub_43b6dedc5117b544_63845_report.xml?apikey=mDK6kWR9e4Nhi-PEnzHWzWR83EdqDacRS-rCzlZXAvWafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KTz-OsETSra7L2kQB-u_gFiE%3D) |
| **docs-ref-conceptual/query-azure-cli.md** | 82 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/query_azure_cli_md_GitHub_43b6dedc5117b544_63846_report.xml?apikey=1Tc3EmQ61fnJIRw1aC6IADNa67UWw1gkLuD2I7wNPw_fAjZ-uWdkfq6FZHSf83ov0IWWHcLjhVqHwiJAaTmlr4ed141Tu_9LFgY5TeGA9IU%3D) |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$

- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/format-output-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/format-output-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/includes/cloud-shell-try-it.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/includes/cloud-shell-try-it.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/includes/cloud-shell-try-it?branch=pr-en-us-380) |
[docs-ref-conceptual/includes/interactive-login.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/includes/interactive-login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/includes/interactive-login?branch=pr-en-us-380) |
[docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/media/cloud-shell-try-it/cs-button.png](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/media/cloud-shell-try-it/cs-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-380) |
[docs-ref-conceptual/overview.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/overview?branch=pr-en-us-380) |
[docs-ref-conceptual/query-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/try-now-cli/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-380) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C2%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201706022324576189-380%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rloutlaw** [comment]
Changes look fine - ready to #sign-off

**Comment by v-thepet** [comment]
@rloutlaw I can merge this, but as I mentioned in another PR: The cloud shell try it language states "Click the Try It button at the top right of a code block to launch the Cloud Shell." But in many cases, the first and other code blocks in the article are not Azure CLI code blocks, so they have no Try It button. This is confusing. Suggest changing the language to: "Click the Try It button at the top right of **an Azure CLI** code block to launch the Cloud Shell." Thanks.

**Pull request merged**
