### PR TITLE
Update titleMapping.json

### PR DESCRIPTION
**Pull request by Juliako**

### CODE REVIEW

**Comment by Juliako** [comment]
#sign-off

**Comment by sptramer** [comment]
@Juliako It looks like the TOC files also need to be updated - check email for the details.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/TOC.yml](https://github.com/Juliako/azure-docs-cli-python/blob/patch-1/latest/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/advisor?view=azure-cli-latest&branch=pr-en-us-800) (azure-cli-latest) |
[titleMapping.json](https://github.com/Juliako/azure-docs-cli-python/blob/patch-1/titleMapping.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C11%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201805111958120834-800%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hOpJt%2FvBc2yULvDOGOalSRwq7%2Fi50yVacQMrebF%2FCZA%3D&st=2018-05-11T19%3A56%3A16Z&se=2018-06-11T20%3A01%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[2017-03-09-profile/docs-ref-autogen/TOC.yml](https://github.com/Juliako/azure-docs-cli-python/blob/patch-1/2017-03-09-profile/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/network/traffic-manager/endpoint?view=azure-cli-2017-03-09-profile&branch=pr-en-us-800) (azure-cli-2017-03-09-profile) |
[latest/docs-ref-autogen/TOC.yml](https://github.com/Juliako/azure-docs-cli-python/blob/patch-1/latest/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/backup/vault?view=azure-cli-latest&branch=pr-en-us-800) (azure-cli-latest) |
[titleMapping.json](https://github.com/Juliako/azure-docs-cli-python/blob/patch-1/titleMapping.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C11%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201805111959156521-800%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e9fsnB%2FY66aBniqrGrzE%2BZ%2BQn3G1kWs%2BtT5KldodDxM%3D&st=2018-05-11T19%3A59%3A14Z&se=2018-06-11T20%3A04%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
