### PR TITLE
Update install-azure-cli.md

### PR DESCRIPTION
**Pull request by ryancrawcour**
Corrected the path for Python scripts in the Note section.
Also, added a reminder that changes to PATH only take effect after you restart your machine.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/ryancrawcour/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-240) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C17%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703171935154572-240%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by allclark** [comment]
#sign-off

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/ryancrawcour/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-240) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C21%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201703211800584602-240%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by KatieCumming** [comment]
@ryancrawcour - Hi Ryan, please resubmit your changes to master instead of Live. Thanks, Katie

**Pull request closed without merging**
