### PR TITLE
Azure CLI 2.0.38 release note

### PR DESCRIPTION
**Pull request by troydai**
Target date 6/19.

### CODE REVIEW

**Comment by troydai** [comment]
@sptramer

**Comment by sptramer** [comment]
@troydai Where are the notes for release 2.0.37? Looks like that was another hotfix.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-5/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-880) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-880) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C14%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806142332376605-880%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SXKIl08ppOtzb7yTYmOpolbhJdt7UtAOhfJE59whYmI%3D&st=2018-06-14T23%3A31%3A03Z&se=2018-07-15T23%3A36%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by troydai** [comment]
Yes. It is minor. Let me add it.

**Comment by troydai** [comment]
Done

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-5/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-880) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-880) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806151615188724-880%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZDzRsU3u4aB3UYlyB3J2UgP%2BQs4tVqfSwz2ZfBO9FOc%3D&st=2018-06-15T16%3A13%3A46Z&se=2018-07-16T16%3A18%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-5/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-880) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-880) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-5/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-880) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-880) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806151810416748-880%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vGmbCblypX3y2mhOed%2BDh2RjO6RPJWwdX%2BRyT8lBFys%3D&st=2018-06-15T18%3A09%3A37Z&se=2018-07-16T18%3A14%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
