### PR TITLE
9/11 Publish

### PR DESCRIPTION
**Pull request by Taojunshen**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Manifest json file &#39;.manifest.json&#39; is invalid. Details: Value cannot be null.
Parameter name: pathUnderSubfolder

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C11%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201709112218438622-481%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Manifest json file &#39;.manifest.json&#39; is invalid. Details: Value cannot be null.
Parameter name: pathUnderSubfolder

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C12%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201709120019244494-481%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Manifest json file &#39;.manifest.json&#39; is invalid. Details: Value cannot be null.
Parameter name: pathUnderSubfolder

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C12%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201709121734265278-481%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
@Taojunshen - There appear to be issues with an autogenerated file that is disrupting our ability to publish at all. Please fix ASAP.

**Pull request closed without merging**
