### PR TITLE
CLI Release 2.0.20 Notes

### PR DESCRIPTION
**Pull request by derekbekoe**

### CODE REVIEW

**Comment by derekbekoe** [comment]
cc: @sptramer @JasonRShaver

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/cli-release-2.0.20/latest/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-latest/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-529) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201710241819139007-529%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5o7%2BhiCLHoekDrrE94PdiSPhCrjoF75N%2FZXKLeW6GVE%3D&st=2017-10-24T18%3A16%3A15Z&se=2017-11-24T18%3A21%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/cli-release-2.0.20/latest/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-latest/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-529) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201710241932426106-529%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZTlI7JAmKOrfBVnUyfHZVbkTS%2BjIGU8JREWHmAz1uPI%3D&st=2017-10-24T19%3A29%3A58Z&se=2017-11-24T19%3A34%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by derekbekoe** [comment]
@sptramer Thanks for the copyedit and merge

**Pull request merged**
