### PR TITLE
Azure CLI 2.0.36 and 2.0.35 Release

### PR DESCRIPTION
**Pull request by troydai**
Azure CLI 2.0.36 will be released on 6/13.
Azure CLI 2.0.35 was a hotfix release which already happened in PyPI and Homebrew.

### CODE REVIEW

**Comment by troydai** [comment]
@sptramer

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-4/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-870) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-870) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806081651057577-870%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zWMnKyM2sY9baWFgr7sA%2FZ5DFrBfQ5qMVtPSbGJR%2Fnc%3D&st=2018-06-08T16%3A49%3A45Z&se=2018-07-09T16%3A54%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
__Do not merge__ until 6/12

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-4/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-870) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-870) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C8%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201806082024499018-870%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7R7627zWNdcI%2B8La2b3gIpThvpJQCmeelMf6SuoYG%2Fs%3D&st=2018-06-08T20%3A23%3A12Z&se=2018-07-09T20%3A28%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by troydai** [comment]
This can be released now.

**Comment by sptramer** [comment]
Thanks for the reminder, merging.

**Pull request merged**
