### PR TITLE
Clarify install/run links

### PR DESCRIPTION
**Pull request by brunoborges**
This change will make it more clear, and visible, where to go for installing or running.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/index.md](https://github.com/brunoborges/azure-docs-cli-python/blob/patch-1/docs-ref-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-latest&branch=pr-en-us-979) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-979) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C9%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201808090512397030-979%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MlDx2fQYUdPk3oafDT7oLCZHv%2BqGq8DJROos9vQbRA4%3D&st=2018-08-09T05%3A11%3A02Z&se=2018-09-09T05%3A16%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
I agree that a change is necessary here, but don't think that this formatting is the correct way to handle the issue (and there would be a number of required edits.) Will leave this PR open for now while I make a decision about how to handle the wording.

**Comment by brunoborges** [comment]
Hi @sptramer, do you have any update on this?

**Comment by sptramer** [comment]
@brunoborges - Sorry, I was out last month doing work related to conferences. This is on my schedule to be picked up in the next week.

**Comment by sptramer** [comment]
Now available as #1015. @brunoborges I made sure to pull your original commit into the history so that you get proper attribution for your changes. Thanks!

**Pull request closed without merging**
