### PR TITLE
update service prinicipal CLI content

### PR DESCRIPTION
**Pull request by rloutlaw**
Review pass of the CLI service principal content based off a suggestion to be more in line with the Powershell content. Reviewed commands for accuracy and conciseness as well as an edit pass for voice.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 77 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_7034_report.xml?apikey=uj0EDh-FA7TKNbGEjXTR4BsiWJs9-QphgIFz1LezganZ2i_AacTjFNTgcRduXy9z9xonL528Bgxrd-sBRqoZ3smUSfL1IEQIRvE6ARSrksk%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by rloutlaw** [comment]
#hold-off

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704052301290958-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 77 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_7168_report.xml?apikey=uCcYSFRlzV_bwUQrkz3g3ZiG3723n1GGu89RMk36dTuafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KT91ixvLqnlRk3ZbQU1zY_uM%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704052351365524-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 76 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_7174_report.xml?apikey=NMsazswgnJHSr-VjrTfnmb6r-XskkOpICCND_WdbRpys0TJw6VhGSu8cGxS2uCt_iMYJCw20W0gld7qhz0udTZd8k5GbWiRTHXl-5GpK3x0%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C6%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704052359423425-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_7249_report.xml?apikey=fqOVZnS_eEYQnPYUITJ3I3-ogsNoSVoUT5H5f2TBDqyafvE6kvCS1vDnVJWC-sUc8xH5DjJyr5K4ed-KT83KTwXvIPGmGqxfGGgy3dpw1Oc%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C6%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704060009104449-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rloutlaw** [comment]
#sign-off

**Comment by rloutlaw** [comment]
@allclark : can you merge this?

**Comment by KatieCumming** [comment]
@rloutlaw - Hi Robert, just a few quick updates are needed and I can merge. Thanks, Katie
#hold-off
Please remove the "en-us" from these 4 URLs so that they are locale agnostic:
[az ad sp create-for-rbac](https://docs.microsoft.com/en-us/cli/azure/ad/sp#create-for-rbac) to create the service principal. 
[az role assignment list](https://docs.microsoft.com/en-us/cli/azure/role/assignment#list) 
[az role assignment create](https://docs.microsoft.com/en-us/cli/azure/role/assignment#create) 
[az role assignment delete](https://docs.microsoft.com/en-us/cli/azure/role/assignment#delete)

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C6%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704061832522818-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/rloutlaw/azure-docs-cli-python/blob/update-ad-sp/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?branch=pr-en-us-288) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C6%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201704061837014011-288%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_13334_report.xml?apikey=w4AEyXGhr2XeAi_5-ANB4ywrjltygrEb_k-o5FHaWGzfAjZ-uWdkfq6FZHSf83ovw3k_TfkA0yyUQJPUjl1KCJQf3WwsuWQsDU7EyZ_TOKU%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Score | Issues | Scorecard |
| ------- | ----- | ------ | --------- |
| **docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md** | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/create_an_azure_service_principal_azure_cli_md_GitHub_49c1a1562f893cf6_13336_report.xml?apikey=mcEW8VUtWa-gZuuFSpMxtbhbP0CQuqpDfDIkSL7oTuXfAjZ-uWdkfq6FZHSf83ovwCxpyHdXBRzFL_FKyXZtlKs5cnCp3FLg56lykhRCBJ0%3D) |

**More info about Acrolinx**
- The scorecard links are good for one hour. If you're prompted to authenticate, you can close and reopen the PR to get new links. Or, use these credentials:
  Account: report-viewer
  Password: kermit$
- [Report false positive results or other issues](https://mseng.visualstudio.com/TechnicalContent/_workItems/create/Task?%5BSystem.Title%5D=Acrolinx%3A+%3Ctitle%3E&%5BSystem.AssignedTo%5D=Tyson+Nevil+%3Ctysonn%40microsoft.com%3E&%5BSystem.Description%5D=%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EPlease+include+the+following+details%3A%3C%2Ffont%3E%3C%2Fdiv%3E%3Cul+style%3D%22color%3A+rgb(0%2C+0%2C+0)%3B+font-family%3A+%26quot%3BSegoe+UI%26quot%3B%2C+Tahoma%2C+Arial%2C+Verdana%3B%22%3E%3Cli%3EA+link+to+the+Acrolinx+report+that+contains+the+issue.%3C%2Fli%3E%3Cli%3EA+detailed+description+of+the+issue.%3C%2Fli%3E%3Cli%3EAttach+screenshot+(optional)%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cfont+color%3D%22%23000000%22+face%3D%22Segoe+UI%2C+Tahoma%2C+Arial%2C+Verdana%22%3EWork+items+that+lack+a+link+to+the+report+and+a+clear+description+will+be+closed.%3C%2Ffont%3E%3C%2Fdiv%3E&%5BSystem.Tags%5D=Acrolinx)

**Comment by rloutlaw** [comment]
Links have been addressed.
 #sign-off

**Comment by allclark** [comment]
@rloutlaw , there are a couple of actionable items in the Acrolinx report.

**Comment by KatieCumming** [comment]
@rloutlaw - thanks for the fixes! This is ready to merge. I'll wait a little longer in case you want to address Allen's comment.

**Pull request merged**
