### PR TITLE
Update release-notes-azure-cli.md for 2.0.44 release

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by troydai** [comment]
@sptramer sorry for coming a bit late.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-8/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-990) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-990) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201808141514526087-990%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=K3hBr87FEclR4gxQHu%2Fc0xwuptOmYyeqONcGTosyxMk%3D&st=2018-08-14T15%3A13%3A11Z&se=2018-09-14T15%3A18%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-8/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-990) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-990) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/troydai/azure-docs-cli-python/blob/patch-8/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-990) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-990) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C14%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201808141727162206-990%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zsNtVZGyALTA1%2Flmsf99h3Hs5iRfTXwopNAlPfM%2B2QI%3D&st=2018-08-14T17%3A25%3A54Z&se=2018-09-14T17%3A30%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by troydai** [comment]
Thank you for the quick turn around.

**Pull request merged**
