### PR TITLE
Refine the docs for installing the Azure CLI on macOS using Homebrew …

### PR DESCRIPTION
**Pull request by conradwt**
The purpose of the PR is to refine the Azure CLI installation on macOS by adding pip install option.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-homebrew.md)
[docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-pip.md)
[docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli.md)
[docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest) | [Details](#user-content-docs-ref-conceptual%2FTOC.yml)
[azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json) | :warning:Warning | | [Details](#user-content-azure-cli-latest%2FTOC.json)

<a name="docs-ref-conceptual%2Finstall-azure-cli-homebrew.md"></a>
### [docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md)
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="docs-ref-conceptual%2Finstall-azure-cli-pip.md"></a>
### [docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md)
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="docs-ref-conceptual%2Finstall-azure-cli.md"></a>
### [docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md)
 - **Line 23**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/install-azure-cli-macos.md).
 - **Line 23**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/install-azure-cli-macos.md).

<a name="docs-ref-conceptual%2FTOC.yml"></a>
### [docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml)
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/install-azure-cli-macos.md).
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/install-azure-cli-macos.md).

<a name="azure-cli-latest%2FTOC.json"></a>
### [azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json)
 - **[Warning]** Error happen when converting azure-cli-latest/TOC.json to Pdf. Details: The process cannot access the file &#39;W:\wo0t-o-unknown\azure-cli-docs_en-us_TOC.pdf&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201810050947540476-1059%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cW4CwgfqNA2tOanG4FAzSExCu2cYNRPaPFPCbR2GMzw%3D&st=2018-10-05T09%3A47%3A06Z&se=2018-11-05T09%3A52%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-homebrew.md)
[docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-pip.md)
[azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json) | :warning:Warning | | [Details](#user-content-azure-cli-latest%2FTOC.json)
[docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |

<a name="docs-ref-conceptual%2Finstall-azure-cli-homebrew.md"></a>
### [docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md)
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="docs-ref-conceptual%2Finstall-azure-cli-pip.md"></a>
### [docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md)
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="azure-cli-latest%2FTOC.json"></a>
### [azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json)
 - **[Warning]** Error happen when converting azure-cli-latest/TOC.json to Pdf. Details: The process cannot access the file &#39;W:\sbdg-o-4ac62035\azure-cli-docs_en-us_TOC.pdf&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201810051001331170-1059%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Fvx%2FJkbxN4ay0yFMZQ2fIuv%2BEIU3GGUemTEv2xdNT%2Fw%3D&st=2018-10-05T10%3A00%3A51Z&se=2018-11-05T10%3A05%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-homebrew.md)
[docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-pip.md)
[azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json) | :warning:Warning | | [Details](#user-content-azure-cli-latest%2FTOC.json)
[docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |

<a name="docs-ref-conceptual%2Finstall-azure-cli-homebrew.md"></a>
### [docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md)
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="docs-ref-conceptual%2Finstall-azure-cli-pip.md"></a>
### [docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md)
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="azure-cli-latest%2FTOC.json"></a>
### [azure-cli-latest/TOC.json](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/azure-cli-latest/TOC.json)
 - **[Warning]** Error happen when converting azure-cli-latest/TOC.json to Pdf. Details: The process cannot access the file &#39;W:\fqmk-o-aca7c19f\azure-cli-docs_en-us_TOC.pdf&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201810051007322587-1059%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oek7mvtrhHc1FIPlk9h1OI1%2B37hS0paee9YbFYNom%2F8%3D&st=2018-10-05T10%3A06%3A56Z&se=2018-11-05T10%3A11%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-homebrew.md)
[docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) | [Details](#user-content-docs-ref-conceptual%2Finstall-azure-cli-pip.md)
[docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |

<a name="docs-ref-conceptual%2Finstall-azure-cli-homebrew.md"></a>
### [docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md)
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 77**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

<a name="docs-ref-conceptual%2Finstall-azure-cli-pip.md"></a>
### [docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md)
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.
 - **Line 78**: **[Warning]** The content part of [!div] syntax is suggested to start in a new line.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201810051009476427-1059%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mrDxEVb0fdPdTXVmyySA7Q6zfKJt5%2FeQyVlx7DDwYdI%3D&st=2018-10-05T10%3A11%3A30Z&se=2018-11-05T10%3A16%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest) |
[docs-ref-conceptual/install-azure-cli-homebrew.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-homebrew.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-homebrew?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/install-azure-cli-pip.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli-pip.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli-pip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/conradwt/azure-docs-cli-python/blob/refine-macos-azure-cli-install/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-1059) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-1059) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201810051029349693-1059%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mTv%2FcQ5XKjsOvJrGf0GrCE1he9KFM1c0q9KsBEiueOo%3D&st=2018-10-05T10%3A28%3A54Z&se=2018-11-05T10%3A33%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
Thanks for your contribution, but unfortunately it has to be rejected at this time.

There have been numerous internal discussions about what to do with pip installation, and we have always come to the conclusion that `pip` is not a suitable install method for most users, and so we shouldn't be documenting it. There are a number of reasons for this, which unfortunately I can't get into publicly without going through a lot of backlog to dig up the full rationale for why this decision has been made each time.

We periodically revisit the `pip` installation issue and will be doing so again before the end of the year.

**Pull request closed without merging**
