### PR TITLE
publish install and interactive content

### PR DESCRIPTION
**Pull request by rloutlaw**

### CODE REVIEW

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) | [Details](#user-content-docs-ref-conceptual%2Finteractive-azure-cli.md)
[docs-ref-autogen/network/application-gateway/url-path-map.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/network/application-gateway/url-path-map.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?branch=pr-en-us-348) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/defaults.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/defaults.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/gestures.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/gestures.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |

<a name="docs-ref-conceptual%2Finteractive-azure-cli.md"></a>
### [docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md)
 - **Line 23**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png).
 - **Line 32**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png).
 - **Line 36**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/defaults.png).
 - **Line 40**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/gestures.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C10%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705101801073729-348%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rloutlaw** [comment]
#sign-off

**Comment by rloutlaw** [comment]
#hold-off

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) | [Details](#user-content-docs-ref-conceptual%2Finteractive-azure-cli.md)
[docs-ref-autogen/cdn/custom-domain.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/cdn/custom-domain.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?branch=pr-en-us-348) |
[docs-ref-autogen/network/application-gateway/url-path-map.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/network/application-gateway/url-path-map.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?branch=pr-en-us-348) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/defaults.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/defaults.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/gestures.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/gestures.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |

<a name="docs-ref-conceptual%2Finteractive-azure-cli.md"></a>
### [docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md)
 - **Line 23**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png).
 - **Line 32**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png).
 - **Line 36**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/defaults.png).
 - **Line 40**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/gestures.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C10%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705101838211398-348%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) | [Details](#user-content-docs-ref-conceptual%2Finteractive-azure-cli.md)
[docs-ref-autogen/cdn/custom-domain.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/cdn/custom-domain.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?branch=pr-en-us-348) |
[docs-ref-autogen/network/application-gateway/url-path-map.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/network/application-gateway/url-path-map.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?branch=pr-en-us-348) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/defaults.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/defaults.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/gestures.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/gestures.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |

<a name="docs-ref-conceptual%2Finteractive-azure-cli.md"></a>
### [docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md)
 - **Line 23**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png).
 - **Line 32**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png).
 - **Line 36**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/defaults.png).
 - **Line 40**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/media/interactive-azure-cli/gestures.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C10%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705101843472517-348%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/Azure/azure-docs-cli-python/blob/master/docfx.json) | :white_check_mark:Succeeded | |
[docs-ref-autogen/cdn/custom-domain.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/cdn/custom-domain.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?branch=pr-en-us-348) |
[docs-ref-autogen/network/application-gateway/url-path-map.pycliyml](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-autogen/network/application-gateway/url-path-map.pycliyml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?branch=pr-en-us-348) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/interactive-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/interactive-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/defaults.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/defaults.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/descriptions-and-examples.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/gestures.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/gestures.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |
[docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/media/interactive-azure-cli/webapp-create.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?branch=pr-en-us-348) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C10%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201705101847241812-348%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rloutlaw** [comment]
#sign-off

**Pull request merged**
