### PR TITLE
C8915: Hardcoded EN locale in link

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @sptramer,

Reported link is hardcoded so it can't lead to target laguages for localized versions. Could you help to merge this PR, please?

Many thanks in advance.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[2017-03-09-profile/docs-ref-conceptual/manage-clouds-azure-cli.md](https://github.com/carolinacmoravia/azure-docs-cli-python/blob/patch-2/2017-03-09-profile/docs-ref-conceptual/manage-clouds-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/manage-clouds-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-571) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C20%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201712201708081986-571%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g3R2QKBvb9r6ld2DT5bhXGaRpCI1sa9zWA%2FnIesyusc%3D&st=2017-12-20T17%3A05%3A43Z&se=2018-01-20T17%3A10%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
#sign-off

**Comment by sptramer** [comment]
@carolinacmoravia I do not have permissions to merge directly to live, and there are other hardcoded `en-us` values. You need to contact Yun Lu if you require an immediate merge. See also PR #572 which will go live today during the normal master->live merge.

**Comment by carolinacmoravia** [comment]
Closing this PR and opening #573

**Pull request closed without merging**
