### PR TITLE
azure-cli 2.0.28 Release Notes

### PR DESCRIPTION
**Pull request by derekbekoe**
To be published, Tuesday February 27, 2018.

### CODE REVIEW

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C23%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802232125299676-654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nOmWakosn0Sy5fuFt378Fz2VVpgb7uLISdcuolZTk08%3D&st=2018-02-23T21%3A23%3A02Z&se=2018-03-26T21%3A28%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by derekbekoe** [comment]
cc: @sptramer  This is to be published 2/27/2018.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C23%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802232329498643-654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=97DZWy5iGyz7uUx4RPk43CBd1e%2F3fXIfRwLr0x9mop0%3D&st=2018-02-23T23%3A27%3A11Z&se=2018-03-26T23%3A32%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802261704528715-654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UXV9SifNN7h4CmswC1xl%2B5s7dKLNCyK2ob%2B5HFnnnaY%3D&st=2018-02-26T17%3A02%3A22Z&se=2018-03-29T17%3A07%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C26%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802261749379057-654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Pg6T1FWGoZ1WOUwMKEg4SrvFJRiXD1eZtsrLDvBTvGs%3D&st=2018-02-26T17%3A47%3A04Z&se=2018-03-29T17%3A52%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sptramer** [comment]
@derekbekoe :+1: will merge tomorrow AM. I should also note that the general quality of release notes from engineering is definitely improving and helps my turnaround time on getting these up much faster. Thank you!

**Comment by derekbekoe** [comment]
@sptramer Please merge when ready.

**Comment by formulahendry** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/install-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |
[docs-ref-conceptual/release-notes-azure-cli.md](https://github.com/derekbekoe/azure-docs-cli-python/blob/az-2.0.28/docs-ref-conceptual/release-notes-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest&branch=pr-en-us-654) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-654) (azure-cli-2017-03-09-profile) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C27%5C0c435b1f-40ec-55c2-6a92-4ae06d82d844%5CPullRequest%5C201802271721392391-654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UoPmhNBL%2F5G6T4hLlgojqW7oClbZ0wiXqrI62mDmmK8%3D&st=2018-02-27T17%3A19%3A07Z&se=2018-03-30T17%3A24%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
